services:
  mongodb:
    build:
      context: db/docker
      dockerfile: MongoDB.dockerfile
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: jNaSQNY8veUG
    volumes:
      - mongodb_data:/etc/mongo

volumes:
  mongodb_data:
